const entryType = {
  ADD_ENTRY: "ADD_ENTRY",
  REMOVE_ENTRY: "REMOVE_ENTRY",
  UPDATE_ENTRY: "UPDATE_ENTRY",
  GET_ENTRIES: "GET_ENTRIES",
  POPULATE_ENTRY: "POPULATE_ENTRY",
  POPULATE_ENTRY_DETAILS: "POPULATE_ENTRY_DETAILS",
  REMOVE_ENTRY_RESULT: "REMOVE_ENTRY_RESULT",
  ADD_ENTRY_RESULT: "ADD_ENTRY_RESULT",
};

export default entryType;
